# Generated by Django 2.1.5 on 2019-01-12 01:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(default='symbol', max_length=10, unique=True)),
                ('name', models.CharField(default='name', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(default='symbol', max_length=10, unique=True)),
                ('ts', models.DateField(default=datetime.datetime(2019, 1, 12, 1, 38, 32, 606672))),
                ('open', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('high', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('low', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('close', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('volume', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
            ],
        ),
    ]
