# Generated by Django 2.1.5 on 2019-01-12 02:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockAnalysis', '0002_auto_20190112_0204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockprice',
            name='ts',
        ),
        migrations.AddField(
            model_name='stockprice',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 1, 12, 2, 5, 26, 31675)),
        ),
    ]
