# Generated by Django 2.1.5 on 2019-02-08 23:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockAnalysis', '0004_auto_20190112_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockprice',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 2, 8, 23, 35, 12, 531596)),
        ),
    ]
