# Generated by Django 2.1.5 on 2019-02-09 01:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockAnalysis', '0005_auto_20190208_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='name',
        ),
        migrations.AddField(
            model_name='stock',
            name='end',
            field=models.DateField(default=datetime.datetime(2019, 2, 9, 1, 42, 53, 550077)),
        ),
        migrations.AddField(
            model_name='stock',
            name='start',
            field=models.DateField(default=datetime.datetime(2019, 2, 9, 1, 42, 53, 550060)),
        ),
        migrations.AlterField(
            model_name='stockprice',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 2, 9, 1, 42, 53, 549704)),
        ),
    ]
