# Generated by Django 2.1.5 on 2019-02-09 02:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockAnalysis', '0006_auto_20190209_0142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='end',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='start',
        ),
        migrations.AddField(
            model_name='stock',
            name='endDate',
            field=models.DateField(default=datetime.datetime(2019, 2, 9, 2, 17, 25, 854823)),
        ),
        migrations.AddField(
            model_name='stock',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2019, 2, 9, 2, 17, 25, 854806)),
        ),
        migrations.AlterField(
            model_name='stockprice',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 2, 9, 2, 17, 25, 854444)),
        ),
    ]
